# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
config,
  ...
}: let
  version = "2.2.7";
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  sops.secrets = {
    "dockers/miniflux/db_url" = {};
    "dockers/miniflux/db_password" = {};
  };
  sops.templates."miniflux-docker.env".content = ''
  DATABASE_URL=${config.sops.placeholder."dockers/miniflux/db_url"}
  POSTGRES_PASSWORD=${config.sops.placeholder."dockers/miniflux/db_password"}
  '';
  # Containers
  virtualisation.oci-containers.containers."miniflux" = {
    image = "docker.io/miniflux/miniflux:${version}";
    environment = {
      "RUN_MIGRATIONS" = "1";
    };
    environmentFiles = [
      config.sops.templates."miniflux-docker.env".path
    ];
    ports = [
      "8031:8080/tcp"
    ];
    dependsOn = [
      "rss-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=/usr/bin/miniflux -healthcheck auto"
      "--network-alias=miniflux"
      "--network=rss_rss_network"
    ];
  };
  systemd.services."docker-miniflux" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-rss_rss_network.service"
    ];
    requires = [
      "docker-network-rss_rss_network.service"
    ];
    partOf = [
      "docker-compose-rss-root.target"
    ];
    wantedBy = [
      "docker-compose-rss-root.target"
    ];
  };
  virtualisation.oci-containers.containers."rss-postgres" = {
    image = "docker.io/postgres:17-alpine";
    environment = {
      "POSTGRES_USER" = "miniflux";
    };
    environmentFiles = [
      config.sops.templates."miniflux-docker.env".path
    ];
    volumes = [
      "rss_miniflux-db:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U miniflux"
      "--health-interval=10s"
      "--health-start-period=30s"
      "--network-alias=db"
      "--network=rss_rss_network"
    ];
  };
  systemd.services."docker-rss-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-rss_rss_network.service"
      "docker-volume-rss_miniflux-db.service"
    ];
    requires = [
      "docker-network-rss_rss_network.service"
      "docker-volume-rss_miniflux-db.service"
    ];
    partOf = [
      "docker-compose-rss-root.target"
    ];
    wantedBy = [
      "docker-compose-rss-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-rss_rss_network" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f rss_rss_network";
    };
    script = ''
      docker network inspect rss_rss_network || docker network create rss_rss_network --driver=bridge
    '';
    partOf = ["docker-compose-rss-root.target"];
    wantedBy = ["docker-compose-rss-root.target"];
  };

  # Volumes
  systemd.services."docker-volume-rss_miniflux-db" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect rss_miniflux-db || docker volume create rss_miniflux-db
    '';
    partOf = ["docker-compose-rss-root.target"];
    wantedBy = ["docker-compose-rss-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-rss-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}

