# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: let
  version = "0.86.1";
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";
  sops.secrets = {
    "dockers/tududi/admin_pass" = {};
    "dockers/tududi/session_secret" = {};
  };
  sops.templates."tududi-docker.env".content = ''
    TUDUDI_USER_PASSWORD=${config.sops.placeholder."dockers/tududi/admin_pass"}
    TUDUDI_SESSION_SECRET=${config.sops.placeholder."dockers/tududi/session_secret"}
  '';

  # Containers
  virtualisation.oci-containers.containers."tududi" = {
    image = "chrisvel/tududi:${version}";
    environment = {
      "GUID" = "1000";
      "PUID" = "1000";
      "TUDUDI_ALLOWED_ORIGINS" = "https://todo.pasqui.casa";
      "TUDUDI_USER_EMAIL" = "info@pasqui.casa";
    };

    environmentFiles = [
      config.sops.templates."tududi-docker.env".path
    ];

    volumes = [
      "/srv/archive/tududi/tududi_db:/app/backend/db:rw"
      "/srv/archive/tududi/tududi_uploads:/app/backend/uploads:rw"
    ];
    ports = [
      "3002:3002/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tududi"
      "--network=tududi_default"
    ];
  };
  systemd.services."docker-tududi" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-tududi_default.service"
    ];
    requires = [
      "docker-network-tududi_default.service"
    ];
    partOf = [
      "docker-compose-tududi-root.target"
    ];
    wantedBy = [
      "docker-compose-tududi-root.target"
    ];
  };
  # Networks
  systemd.services."docker-network-tududi_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f tududi_default";
    };
    script = ''
      docker network inspect tududi_default || docker network create tududi_default               '';
    partOf = ["docker-compose-tududi-root.target"];
    wantedBy = ["docker-compose-tududi-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-tududi-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
