# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: let
  version = "v0.17.1";
in {
  homelab.tunnelRoutes = {
    "fit.pasqui.casa" = "http://localhost:3004";
  };

  # Runtime
  sops.secrets = {
    "sparkyfitness/db_password" = {};
    "sparkyfitness/better_auth_secret" = {};
    "sparkyfitness/app_db_password" = {};
    "sparkyfitness/api_encryption_key" = {};
  };

  sops.templates."sparkyfitness.env".content = ''
    SPARKY_FITNESS_DB_PASSWORD=${config.sops.placeholder."sparkyfitness/db_password"}
    POSTGRES_PASSWORD=${config.sops.placeholder."sparkyfitness/db_password"}
    BETTER_AUTH_SECRET=${config.sops.placeholder."sparkyfitness/better_auth_secret"}
    SPARKY_FITNESS_APP_DB_PASSWORD=${config.sops.placeholder."sparkyfitness/app_db_password"}
    SPARKY_FITNESS_API_ENCRYPTION_KEY=${config.sops.placeholder."sparkyfitness/api_encryption_key"}
  '';
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."sparkyfitness-db" = {
    image = "postgres:18.3-alpine";
    environment = {
      "GUID" = "1000";
      "POSTGRES_DB" = "sparkyfitness_db";
      "POSTGRES_USER" = "sparky";
      "PUID" = "1000";
    };
    environmentFiles = [config.sops.templates."sparkyfitness.env".path];
    volumes = [
      "/home/hspasqui/docker-compose/sparky-fitness/postgresql:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-db"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };
  # MCP is now served internally by the server at /mcp (in-process).
  # The dedicated MCP container is deprecated and removed.
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-frontend" = {
    image = "codewithcj/sparkyfitness:latest";
    environment = {
      "GUID" = "1000";
      "PUID" = "1000";
      "SPARKY_FITNESS_FRONTEND_URL" = "https://fit.pasqui.casa";
      "SPARKY_FITNESS_SERVER_HOST" = "sparkyfitness-server";
      "SPARKY_FITNESS_SERVER_PORT" = "3010";
    };
    ports = [
      "3004:80/tcp"
    ];
    dependsOn = [
      "sparkyfitness-sparkyfitness-server"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-frontend"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-sparkyfitness-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-server" = {
    image = "codewithcj/sparkyfitness_server:${version}";
    environment = {
      "ALLOW_PRIVATE_NETWORK_CORS" = "false";
      "GUID" = "1000";
      "PUID" = "1000";
      "SPARKY_FITNESS_ADMIN_EMAIL" = "lorenzo@pasqui.casa";
      "SPARKY_FITNESS_APP_DB_USER" = "sparky_app";
      "SPARKY_FITNESS_DB_HOST" = "sparkyfitness-db";
      "SPARKY_FITNESS_DB_NAME" = "sparkyfitness_db";
      "SPARKY_FITNESS_DB_PORT" = "5432";
      "SPARKY_FITNESS_DB_USER" = "sparky";
      "SPARKY_FITNESS_DISABLE_SIGNUP" = "true";
      "SPARKY_FITNESS_EMAIL_FROM" = "";
      "SPARKY_FITNESS_EMAIL_HOST" = "";
      "SPARKY_FITNESS_EMAIL_PASS" = "";
      "SPARKY_FITNESS_EMAIL_PORT" = "";
      "SPARKY_FITNESS_EMAIL_SECURE" = "";
      "SPARKY_FITNESS_EMAIL_USER" = "";
      "SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS" = "";
      "SPARKY_FITNESS_FRONTEND_URL" = "https://fit.pasqui.casa";
      "SPARKY_FITNESS_LOG_LEVEL" = "ERROR";
      "SPARKY_FITNESS_PUBLIC_API_DOCS" = "false";
    };
    environmentFiles = [config.sops.templates."sparkyfitness.env".path];

    volumes = [
      "/home/hspasqui/docker-compose/sparky-fitness/backup:/app/SparkyFitnessServer/backup:rw"
      "/home/hspasqui/docker-compose/sparky-fitness/uploads:/app/SparkyFitnessServer/uploads:rw"
    ];
    dependsOn = [
      "sparkyfitness-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-server"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-sparkyfitness-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-sparkyfitness_sparkyfitness-network" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f sparkyfitness_sparkyfitness-network";
    };
    script = ''
      docker network inspect sparkyfitness_sparkyfitness-network || docker network create sparkyfitness_sparkyfitness-network --driver=bridge
    '';
    partOf = ["docker-compose-sparkyfitness-root.target"];
    wantedBy = ["docker-compose-sparkyfitness-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-sparkyfitness-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
