# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: let
  version = "v0.17.2";
in {
  homelab.tunnelRoutes = {
    "fit.pasqui.casa" = "http://localhost:3004";
  };

  # Runtime
  sops.secrets = {
    "sparkyfitness/db_password" = {};
    "sparkyfitness/better_auth_secret" = {};
    "sparkyfitness/app_db_password" = {};
    "sparkyfitness/api_encryption_key" = {};
    "sparkyfitness/oidc_client_id" = {};
    "sparkyfitness/oidc_client_secret" = {};
  };

  sops.templates."sparkyfitness.env".content = ''
    SPARKY_FITNESS_DB_PASSWORD=${config.sops.placeholder."sparkyfitness/db_password"}
    POSTGRES_PASSWORD=${config.sops.placeholder."sparkyfitness/db_password"}
    BETTER_AUTH_SECRET=${config.sops.placeholder."sparkyfitness/better_auth_secret"}
    SPARKY_FITNESS_APP_DB_PASSWORD=${config.sops.placeholder."sparkyfitness/app_db_password"}
    SPARKY_FITNESS_API_ENCRYPTION_KEY=${config.sops.placeholder."sparkyfitness/api_encryption_key"}
    # OIDC / Authentik
    SPARKY_FITNESS_OIDC_AUTH_ENABLED=true
    SPARKY_FITNESS_OIDC_CLIENT_ID=${config.sops.placeholder."sparkyfitness/oidc_client_id"}
    SPARKY_FITNESS_OIDC_CLIENT_SECRET=${config.sops.placeholder."sparkyfitness/oidc_client_secret"}
  '';
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."sparkyfitness-db" = {
    image = "postgres:18.3-alpine";
    environment = {
      "GUID" = "1000";
      "POSTGRES_DB" = "sparkyfitness_db";
      "POSTGRES_USER" = "sparky";
      "PUID" = "1000";
    };
    environmentFiles = [config.sops.templates."sparkyfitness.env".path];
    volumes = [
      "/home/hspasqui/docker-compose/sparky-fitness/postgresql:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-db"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };
  # MCP is now served internally by the server at /mcp (in-process).
  # The dedicated MCP container is deprecated and removed.
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-frontend" = {
    image = "codewithcj/sparkyfitness:${version}";
    environment = {
      "GUID" = "1000";
      "PUID" = "1000";
      "SPARKY_FITNESS_FRONTEND_URL" = "https://fit.pasqui.casa";
      "SPARKY_FITNESS_SERVER_HOST" = "sparkyfitness-server";
      "SPARKY_FITNESS_SERVER_PORT" = "3010";
    };
    ports = [
      "3004:80/tcp"
    ];
    dependsOn = [
      "sparkyfitness-sparkyfitness-server"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-frontend"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-sparkyfitness-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sparkyfitness-sparkyfitness-server" = {
    image = "ghcr.io/l0r3v/sparkyfitness-server:latest";
    environment = {
      "ALLOW_PRIVATE_NETWORK_CORS" = "false";
      "GUID" = "1000";
      "PUID" = "1000";
      "SPARKY_FITNESS_APP_DB_USER" = "sparky_app";
      "SPARKY_FITNESS_DB_HOST" = "sparkyfitness-db";
      "SPARKY_FITNESS_DB_NAME" = "sparkyfitness_db";
      "SPARKY_FITNESS_DB_PORT" = "5432";
      "SPARKY_FITNESS_DB_USER" = "sparky";
      "SPARKY_FITNESS_DISABLE_SIGNUP" = "false";
      "SPARKY_FITNESS_EMAIL_FROM" = "";
      "SPARKY_FITNESS_EMAIL_HOST" = "";
      "SPARKY_FITNESS_EMAIL_PASS" = "";
      "SPARKY_FITNESS_EMAIL_PORT" = "";
      "SPARKY_FITNESS_EMAIL_SECURE" = "";
      "SPARKY_FITNESS_EMAIL_USER" = "";
      "SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS" = "";
      "SPARKY_FITNESS_FRONTEND_URL" = "https://fit.pasqui.casa";
      "SPARKY_FITNESS_LOG_LEVEL" = "ERROR";
      "SPARKY_FITNESS_PUBLIC_API_DOCS" = "false";
      # OIDC / Authentik — non-secret (secrets are in sops template)
      "SPARKY_FITNESS_OIDC_ISSUER_URL" = "https://auth.pasqui.casa/application/o/sparkyfitness/";
      "SPARKY_FITNESS_OIDC_PROVIDER_SLUG" = "sparkyfitness";
      "SPARKY_FITNESS_OIDC_PROVIDER_NAME" = "Log in with Authentik";
      "SPARKY_FITNESS_OIDC_SCOPE" = "openid email group profile";
      "SPARKY_FITNESS_OIDC_TOKEN_AUTH_METHOD" = "client_secret_post";
      "SPARKY_FITNESS_OIDC_AUTO_REGISTER" = "true";
      "SPARKY_FITNESS_OIDC_ADMIN_GROUP" = "sparky_admin";
      "SPARKY_FITNESS_DISABLE_EMAIL_LOGIN" = "true";
    };
    environmentFiles = [config.sops.templates."sparkyfitness.env".path];

    volumes = [
      "/home/hspasqui/docker-compose/sparky-fitness/backup:/app/SparkyFitnessServer/backup:rw"
      "/home/hspasqui/docker-compose/sparky-fitness/uploads:/app/SparkyFitnessServer/uploads:rw"
    ];
    dependsOn = [
      "sparkyfitness-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sparkyfitness-server"
      "--network=sparkyfitness_sparkyfitness-network"
    ];
  };
  systemd.services."docker-sparkyfitness-sparkyfitness-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    requires = [
      "docker-network-sparkyfitness_sparkyfitness-network.service"
    ];
    partOf = [
      "docker-compose-sparkyfitness-root.target"
    ];
    wantedBy = [
      "docker-compose-sparkyfitness-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-sparkyfitness_sparkyfitness-network" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f sparkyfitness_sparkyfitness-network";
    };
    script = ''
      docker network inspect sparkyfitness_sparkyfitness-network || docker network create sparkyfitness_sparkyfitness-network --driver=bridge
    '';
    partOf = ["docker-compose-sparkyfitness-root.target"];
    wantedBy = ["docker-compose-sparkyfitness-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-sparkyfitness-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };

  # ── Backup ──────────────────────────────────────────────────────
  # Nightly pg_dump → BorgBase (compressed SQL dump)
  systemd.timers."backup-sparkyfitness" = {
    wantedBy = ["timers.target"];
    timerConfig = {
      OnCalendar = "03:00";
      Persistent = true;
      RandomizedDelaySec = 300;
    };
  };

  systemd.services."backup-sparkyfitness" = {
    path = with pkgs; [borgbackup gzip postgresql_18 docker curl util-linux];
    script = ''
      #!/bin/sh
      set -eu

      STATUS=0
      TELEGRAM_BOT_TOKEN="$(cat ${config.sops.secrets.telegram_bot_token.path})"
      DUMP_FILE="/tmp/sparkyfitness-dump.sql.gz"

      export BORG_PASSCOMMAND="cat ${config.sops.secrets."borgbase/passphrase".path}"
      export BORG_RSH="ssh -i ${config.sops.secrets."borgbase/ssh_key".path} -o StrictHostKeyChecking=no"
      REMOTE_HOST=$(cat ${config.sops.secrets."borgbase/forgejo/remote_host".path})
      REPO="$REMOTE_HOST./repo"

      start_time=$(date +%s)
      echo "=== SparkyFitness backup ==="
      echo "Dumping PostgreSQL database..."

      docker exec sparkyfitness-db pg_dump -U sparky sparkyfitness_db \
        | gzip > "$DUMP_FILE"

      DUMP_SIZE=$(du -h "$DUMP_FILE" | cut -f1)
      echo "Dump size: $DUMP_SIZE"

      echo "Sending to BorgBase..."
      borg create \
        --compression lz4 \
        --stats \
        "$REPO::{now}" \
        "$DUMP_FILE" || STATUS=$?

      rm -f "$DUMP_FILE"

      end_time=$(date +%s)
      duration=$((end_time - start_time))
      minutes=$((duration / 60))
      seconds=$((duration % 60))

      if [ "$STATUS" -eq 0 ]; then
        MSG="✅ SparkyFitness backup completato con successo"
      else
        MSG="❌ Errore nel backup SparkyFitness (exit $STATUS) @Lorevocator"
      fi

      echo "Status $STATUS: $MSG"
      curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
        -d chat_id=-1002509650347 \
        -d message_thread_id=5596 \
        -d text="#sparky: $MSG. Tempo impiegato: $minutes min e $seconds sec ($DUMP_SIZE)"

      exit $STATUS
    '';

    serviceConfig = {
      Type = "oneshot";
      User = "root";
      LogsDirectory = "backup-sparkyfitness";
    };
    restartIfChanged = false;
  };
}
