name: Update Nix Flakes and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' 

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Installa Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Aggiorna flake.lock e crea PR
        uses: DeterminateSystems/update-flake-lock@main

      - name: Create Pull Request
        uses: infinilabs/gitea-pr@v0
        with:
          url: ${{ secrets.GITEA_URL }}
          token: ${{ secrets.GITEA_TOKEN }}
          base: 'main'
          branch: 'flake-update-latest'
          title: 'chore: update flakes'
          body: 'Updated flake.lock file'
