# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."grimmory" = {
    image = "grimmory/grimmory:v0.38.2";
    environment = {
      "DATABASE_PASSWORD" = "your_secure_password";
      "DATABASE_URL" = "jdbc:mariadb://mariadb:3306/grimmory";
      "DATABASE_USERNAME" = "grimmory";
      "FORCE_DISABLE_OIDC" = "false";
      "GROUP_ID" = "1000";
      "SWAGGER_ENABLED" = "false";
      "TZ" = "Etc/UTC";
      "USER_ID" = "1000";
    };
    volumes = [
      "/home/lorev/nixos/homelab/dockers/grimmory/bookdrop:/bookdrop:rw"
      "/home/lorev/nixos/homelab/dockers/grimmory/books:/books:rw"
      "/home/lorev/nixos/homelab/dockers/grimmory/data:/app/data:rw"
    ];
    ports = [
      "6060:6060/tcp"
    ];
    dependsOn = [
      "grimmory-mariadb"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=grimmory"
      "--network=grimmory_default"
    ];
  };
  systemd.services."docker-grimmory" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-grimmory_default.service"
    ];
    requires = [
      "docker-network-grimmory_default.service"
    ];
    partOf = [
      "docker-compose-grimmory-root.target"
    ];
    wantedBy = [
      "docker-compose-grimmory-root.target"
    ];
  };
  virtualisation.oci-containers.containers."grimmory-mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.8";
    environment = {
      "MYSQL_DATABASE" = "grimmory";
      "MYSQL_PASSWORD" = "your_secure_password";
      "MYSQL_ROOT_PASSWORD" = "super_secure_password";
      "MYSQL_USER" = "grimmory";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/home/lorev/nixos/homelab/dockers/grimmory/config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=grimmory_default"
    ];
  };
  systemd.services."docker-grimmory-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-grimmory_default.service"
    ];
    requires = [
      "docker-network-grimmory_default.service"
    ];
    partOf = [
      "docker-compose-grimmory-root.target"
    ];
    wantedBy = [
      "docker-compose-grimmory-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-grimmory_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f grimmory_default";
    };
    script = ''
      docker network inspect grimmory_default || docker network create grimmory_default
    '';
    partOf = [ "docker-compose-grimmory-root.target" ];
    wantedBy = [ "docker-compose-grimmory-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-grimmory-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
