# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  sops.secrets = {
    "dockers/gitea/db_password" = {};
    "dockers/gitea/ssh_domain" = {};
  };
  sops.templates."gitea-docker.env".content = ''
    SSH_DOMAIN=${config.sops.placeholder."dockers/gitea/ssh_domain"}
    GITEA__database__PASSWD=${config.sops.placeholder."dockers/gitea/db_password"}
    POSTGRES_PASSWORD=${config.sops.placeholder."dockers/gitea/db_password"}
  '';
  # Containers
  virtualisation.oci-containers.containers."gitea" = {
    image = "docker.gitea.com/gitea:1.23";
    environment = {
      "GITEA__database__DB_TYPE" = "postgres";
      "GITEA__database__HOST" = "db:5432";
      "GITEA__database__NAME" = "gitea";
      "GITEA__database__USER" = "gitea";
      "USER_GID" = "1000";
      "USER_UID" = "1000";
      "DISABLE_REGISTRATION" = "true";
      "REQUIRE_SIGNIN_VIEW" = "false";
      "SSH_PORT" = "22";
    };
    environmentFiles = [
      config.sops.templates."gitea-docker.env".path
    ];
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/etc/timezone:/etc/timezone:ro"
      "/srv/archive/gitea/data:/data:rw"
    ];
    ports = [
      "8222:3000/tcp"
      "2221:22/tcp"
    ];
    dependsOn = [
      "gitea-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=server"
      "--network=gitea_gitea"
    ];
  };
  systemd.services."docker-gitea" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gitea_gitea.service"
    ];
    requires = [
      "docker-network-gitea_gitea.service"
    ];
    partOf = [
      "docker-compose-gitea-root.target"
    ];
    wantedBy = [
      "docker-compose-gitea-root.target"
    ];
  };
  virtualisation.oci-containers.containers."gitea-db" = {
    image = "docker.io/library/postgres:14";
    environment = {
      "POSTGRES_DB" = "gitea";
      "POSTGRES_USER" = "gitea";
    };
    environmentFiles = [
      config.sops.templates."gitea-docker.env".path
    ];
    volumes = [
      "/srv/archive/gitea/postgres:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=gitea_gitea"
    ];
  };
  systemd.services."docker-gitea-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gitea_gitea.service"
    ];
    requires = [
      "docker-network-gitea_gitea.service"
    ];
    partOf = [
      "docker-compose-gitea-root.target"
    ];
    wantedBy = [
      "docker-compose-gitea-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-gitea_gitea" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f gitea_gitea";
    };
    script = ''
      docker network inspect gitea_gitea || docker network create gitea_gitea
    '';
    partOf = ["docker-compose-gitea-root.target"];
    wantedBy = ["docker-compose-gitea-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-gitea-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
