# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  ...
}: let
  version = "26.1.0";
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."actual_server-actual_server" = {
    image = "docker.io/actualbudget/actual-server:${version}";
    environment = {
      "ACTUAL_PORT" = "5006";
      "ACTUAL_LOGIN_METHOD" = "openid";
    };
    volumes = [
      "/srv/archive/actual-budget/actual-data:/data:rw"
    ];
    ports = [
      "5006:5006/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=node src/scripts/health-check.js"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=10s"
      "--network-alias=actual_server"
      "--network=actual_server_default"
    ];
  };
  systemd.services."docker-actual_server-actual_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-actual_server_default.service"
    ];
    requires = [
      "docker-network-actual_server_default.service"
    ];
    partOf = [
      "docker-compose-actual_server-root.target"
    ];
    wantedBy = [
      "docker-compose-actual_server-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-actual_server_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f actual_server_default";
    };
    script = ''
      docker network inspect actual_server_default || docker network create actual_server_default
    '';
    partOf = ["docker-compose-actual_server-root.target"];
    wantedBy = ["docker-compose-actual_server-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-actual_server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
