# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  ...
}: let
  version = "0.6.24";
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."calibre-web" = {
    image = "lscr.io/linuxserver/calibre-web:${version}";
    environment = {
      "DOCKER_MODS" = "linuxserver/mods:universal-calibre";
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Europe/Rome";
    };
    volumes = [
      "/srv/archive/calibre-web/data:/config:rw"
      "/srv/archive/calibre-web/library:/books:rw"
    ];
    ports = [
      "8083:8083/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=calibre-web"
      "--network=libreria-pasqui_default"
    ];
  };
  systemd.services."docker-calibre-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-libreria-pasqui_default.service"
    ];
    requires = [
      "docker-network-libreria-pasqui_default.service"
    ];
    partOf = [
      "docker-compose-libreria-pasqui-root.target"
    ];
    wantedBy = [
      "docker-compose-libreria-pasqui-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-libreria-pasqui_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f libreria-pasqui_default";
    };
    script = ''
      docker network inspect libreria-pasqui_default || docker network create libreria-pasqui_default
    '';
    partOf = ["docker-compose-libreria-pasqui-root.target"];
    wantedBy = ["docker-compose-libreria-pasqui-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-libreria-pasqui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
