name: Update Nix Flakes and Create PR

on:
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch:
jobs:
  update-flake:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

        # Aggiorna flake di XPSnixos
      - name: Aggiorna flake.lock e crea PR XPSnixos
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flakes in XPSnixos"
          pr-labels: automated
          path-to-flake-dir: 'XPSnixos/'
      - name: Aggiorna flake.lock e crea PR homelab
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flakes in homelab"
          pr-labels: automated
          path-to-flake-dir: 'homelab/'
