name: Update Homelab Nix Flakes and Create PR

on:
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch:
jobs:
  update-flake:
    permissions:
      contents: write
      pull-requests: write
    runs-on: nixos-host
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Aggiorna flake.lock
        run: | 
          git config user.name "l0r3v"
          git config user.email "lorenzopasqui@gmail.com"
          git fetch origin
          git remote set-url origin https://gitea-bot:${GITEA_PAT}@git.pasqui.casa/lorev/nixos.git
          if git ls-remote --exit-code --heads origin flake-update-homelab; then
            git checkout flake-update-homelab
            git pull --rebase origin flake-update-homelab 
            echo "branch esiste"
          else
            git checkout -b flake-update-homelab
          fi
          nix flake update --flake homelab/.
          git config user.name "gitea-bot"
          git config user.email "info@pasqui.casa"
          echo DIFF:
          echo $(git diff --name-only)
          echo $(git status --porcelain)
          if git status --porcelain | grep -q 'homelab/flake.lock'; then
            git add homelab/flake.lock
            git commit -m "chore: updated flakes"
            git push origin HEAD
            tea login delete git.pasqui.casa 2>/dev/null || true
            tea login add -u https://git.pasqui.casa -t ${GITEA_PAT}
            tea pr create --head flake-update-homelab --base main --title "chore: update homelab flakes" -a "lorev" -L "host/homelab" --repo lorev/nixos
          else
            echo "Nessun cambiamento da committare"
          fi
        env: 
          NIX_CONFIG: "access-tokens = github.com=${{ secrets.GH_TOKEN }}"
          GITEA_PAT: ${{ secrets.PAT }}
