# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  sops.secrets = {
    "dockers/cloudflared/tunnel_token" = {};
  };
  sops.templates."cloudflared-docker.env".content = ''
    TUNNEL_TOKEN=${config.sops.placeholder."dockers/cloudflared/tunnel_token"}
  '';
  # Containers
  virtualisation.oci-containers.containers."cloudflare-tunnel" = {
    image = "cloudflare/cloudflared";
    environmentFiles = [
      config.sops.templates."cloudflared-docker.env".path
    ];
    cmd = ["tunnel" "run"];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=cloudflared"
      "--network=cloudflared_default"
    ];
  };
  systemd.services."podman-cloudflare-tunnel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-cloudflared_default.service"
    ];
    requires = [
      "podman-network-cloudflared_default.service"
    ];
    partOf = [
      "podman-compose-cloudflared-root.target"
    ];
    wantedBy = [
      "podman-compose-cloudflared-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-cloudflared_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f cloudflared_default";
    };
    script = ''
      podman network inspect cloudflared_default || podman network create cloudflared_default
    '';
    partOf = ["podman-compose-cloudflared-root.target"];
    wantedBy = ["podman-compose-cloudflared-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-cloudflared-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
